replicaCount: 1

image:
  repository: mayth/simple-upload-server@sha256
  pullPolicy: IfNotPresent
  tag: b0e711dcdfe9be60ed20ef5447a20dbd42f467c7f16772c0581241f9e82ea9ec

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}
livenessProbe:
  tcpSocket:
    port: http
readinessProbe:
  tcpSocket:
    port: http

autoscaling:
  enabled: false

envs:
  - name: TOKEN
    valueFrom:
      secretKeyRef:
        name: read-write-tokens
        key: token
containerArgs:
  - "-enable_auth"
  - "-read_write_tokens=$(TOKEN)"
  - "-max_upload_size=1048576"
  - "-addr=0.0.0.0:8080"
  - "-document_root=/widgetapi/data"
pvc:
  size: 1Gi
volumes:
  - name: datavol
    persistentVolumeClaim:
      claimName: uploads-pvc

volumeMounts:
 - name: datavol
   mountPath: "/widgetapi/data"
   readOnly: false

nodeSelector: {}

tolerations: []

affinity: {}
