apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-egress
spec:
  podSelector:
    matchLabels:{{ include "small-helm-chart.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-ingress
spec:
  podSelector:
    matchLabels:{{ include "small-helm-chart.selectorLabels" . | nindent 6 }}
  ingress:
  - {}
  policyTypes:
  - Ingress